CREATE TABLE "GCG_3983_STANDBY"(
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "SEQ" CHAR(6),
 "REASON" CHAR(30),
 "DATE_DOWN" DATE,
 "BEGIN_TIME" TIME,
 "END_TIME" TIME,
 "EMPLOYEE" CHAR(5),
 "NAME_EMPLOYEE" CHAR(30),
 "TOTAL_MINUTES" NUMERIC(12,4));
